import type { Metadata } from "next";
import "../globals.css";
import Header from "@/app/widget/Header";
import localFont from "next/font/local"


const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mt-14 ${pretendard.variable} font-pretendard`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
